name: tower-action
author: Phil Ewels

description: Launch a workflow using Nextflow Tower (https://tower.nf)

branding:
  icon: 'play'
  color: 'purple'

inputs:
  # I'd like to rename this to access_token for consistency after it was renamed by Tower
  # but need to keep it like this for backwards compatibility in existing pipelines
  bearer_token:
    description: Nextflow Tower access token
    required: true
  compute_env:
    description: Nextflow Tower compute env
    required: true
  workspace_id:
    description: Nextflow Tower workspace ID
    required: false
  pipeline:
    description: Pipeline repository
    default: ${{ github.repository }}
    required: false
  revision:
    description: Pipeline revision (release / branch)
    default: ${{ github.sha }}
    required: false
  workdir:
    description: Nextflow work directory
    required: true
  parameters:
    description: Pipeline parameters
    default: '{}'
    required: false
  profiles:
    description: Nextflow config profiles
    default: '[]'
    required: false

runs:
  using: 'docker'
  image: Dockerfile
  env:
    TOWER_WORKSPACE_ID: ${{ inputs.workspace_id }}
    TOWER_ACCESS_TOKEN: ${{ inputs.bearer_token }}
    TOWER_COMPUTE_ENV: ${{ inputs.compute_env }}
    PIPELINE: ${{ inputs.pipeline }}
    REVISION: ${{ inputs.revision }}
    WORKDIR: ${{ inputs.workdir }}
    PARAMETERS: ${{ toJson(fromJson(inputs.parameters)) }}
    CONFIG_PROFILES: ${{ toJson(fromJson(inputs.profiles)) }}
